// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Nower is an autogenerated mock type for the Nower type
type Nower struct {
	mock.Mock
}

// Now provides a mock function with given fields:
func (_m *Nower) Now() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
